
# Alpha diversity analysis

```{r setup, include=FALSE}
library(knitr)
library(knitcitations) 
library(microbiome)
library(phyloseq)
library(ggplot2)
library(reshape2)
library(tidyverse)
library(dada2)
library(dplyr)
library(vegan)
library(ggpubr)
library(gridExtra)
theme_set(theme_bw(20))
# Was created with: source("create_phyloseq.R")
physeqnew <- readRDS("inputdata/processed/phyloseq/physeqnew.RDS")
temp.phy <- filter_taxa(physeqnew, function (x) {sum(x > 0) > 1}, prune=TRUE)
```


## Estimate alpha diversities

### with respect to Family

```{r alpha, echo=FALSE, message=FALSE, warning=FALSE}
A <- alpha(temp.phy)
df <- meta(temp.phy)
df <- bind_cols(df, A)
index <- "diversity_shannon"
df$index <- df[[index]]
pv <- kruskal.test(data = df, index ~ factor(Family))$p.value
kruskal.test(data = df, index ~ factor(Family))
library(ggbeeswarm)
library(ggsignif)
#p1 <- ggplot(df, aes(x = Family, y = index, color = Family)) + geom_jitter(position=position_jitter(0.1), cex=2.0) +                     
#theme(legend.position="none") + 
#       labs(y = "Shannon index", x = "Family") + title = paste0("Kruskal test p=", round(pv, 2))
p1 <- ggplot(df, aes(x = Family, y = index, color = Family)) +
      geom_boxplot() + theme(legend.position="top", legend.title = element_text("Stats"))  +
       geom_jitter(width = 0.1) +  
	theme(axis.text.x = element_text(angle = 0, hjust = 0.5),axis.title.x = element_text()) +
 labs(y = "Shannon Diversity", x = "", title = "Family") + theme(legend.position = "none")

print(p1)
```

### Diet

```{r alpha Diet, echo=FALSE, message=FALSE, warning=FALSE}
#A <- alpha(temp.phy)
df <- meta(temp.phy)
df <- bind_cols(df, A)
index <- "diversity_shannon"
df$index <- df[[index]]
ppv <- wilcox.test(data = df, index ~ factor(Diet))$p.value
wilcox.test(data = df, index ~factor(Diet))
p2 <- ggplot(df, aes(x = Diet, y = index, color = Diet)) +
        geom_boxplot() +
       geom_jitter(width = 0.05) +
	theme(axis.text.x = element_text(angle = 0, hjust = 0.5),axis.title.x = element_text()) +scale_x_discrete(limits = c("Mixed", "Veg"),
                       labels = c("Mixed", "Vegetarian")) +theme(legend.position = "none")+
        labs(y = "Shannon Diversity",
	     x = "",
	     title = "Diet") + geom_signif(comparisons = list(c("Mixed", "Veg")), map_signif_level = TRUE)

#print(p2)
## Multiple pairwise comparison 
qw <- subset(df, Diet %in% c("Mixed", "Veg"))
renu <- wilcox.test(data = qw, index ~ factor(Diet))$p.value
wilcox.test(data = qw, index ~factor(Diet))
p.adjust(c(0.001,0.01,0.05,0.1), method = "bonferroni")
```

### Age

```{r alpha age, echo=FALSE, message=FALSE, warning=FALSE}
#A <- alpha(temp.phy)
df <- meta(temp.phy)
df <- bind_cols(df, A)
index <- "diversity_shannon"
df$index <- df[[index]]
pv <- kruskal.test(data = df, index ~ factor(Age))$p.value
kruskal.test(data = df, index ~factor(Age))
p3 <- ggplot(df, aes(x = Age, y = index, color = Age)) +  geom_boxplot() + geom_jitter(position=position_jitter(0.1), cex=2.0) +                     theme(legend.position="none") + 
           theme(axis.title.x = element_text()) + scale_x_discrete(limits = c("Adult", "Elderly", "Middle_age"), labels = c("Adult", "Elderly", "Middle age")) +
       labs(y = "Shannon Diversity", x = "Age", title = "Age") + geom_signif(comparisons = list(c("Mixed", "Veg")), map_signif_level = TRUE) 
#print(p3)

## Multiple pairwise comparison 
RE <- subset(df, Age %in% c("Adult", "Middle_age"))
Renz <- wilcox.test(data = RE, index ~ factor(Age))$p.value
wilcox.test(data = RE, index ~factor(Age))
NU<- subset(df, Age %in% c("Adult", "Elderly"))
RUK <- wilcox.test(data = NU, index ~ factor(Age))$p.value
wilcox.test(data = NU, index ~factor(Age))
KA<- subset(df, Age %in% c("Middle_age", "Elderly"))
RUS <- wilcox.test(data = KA, index ~ factor(Age))$p.value
wilcox.test(data = KA, index ~factor(Age))
p.adjust(c(0.001,0.01,0.05,0.1), method = "bonferroni")
```

### Gender

```{r alpha gender, echo=FALSE, message=FALSE, warning=FALSE}
#A <- alpha(temp.phy)
df <- meta(temp.phy)
df <- bind_cols(df, A)
index <- "diversity_shannon"
df$index <- df[[index]]
pv <- wilcox.test(data = df, index ~ factor(Gender))$p.value
wilcox.test(data = df, index ~ factor(Gender))

p4 <- ggplot(df, aes(x = Gender, y = index, color = Gender)) +
        geom_boxplot() + geom_jitter(width = 0.05) +
	theme(axis.text.x = element_text(angle = 0, hjust = 0.5),axis.title.x = element_text()) +theme(legend.position = "none")+
        labs(y = "Shannon Diversity",
	     x = "",
	     title = "Gender") #+ geom_signif(comparisons = list(c("Male", "Female")), map_signif_level = TRUE)
#print(p4)
```

### Geographical Location


```{r diffab, echo=FALSE, echo=FALSE, message=FALSE, warning=FALSE, fig.width=8, fig.height=7, fig.show="keep", out.width="60%"}
df <- meta(temp.phy)
df <- bind_cols(df, A)
index <- "diversity_shannon"
df$index <- df[[index]]
pv <- wilcox.test(data = df, index ~ factor(Location))$p.value
wilcox.test(data = df, index ~factor(Location))
library(ggbeeswarm)
library(ggsignif)
p5 <- ggplot(df, aes(x = Location, y = index, color = Location)) +
       geom_boxplot() + theme(legend.position="top", legend.title = element_text("Stats"))  +
       geom_jitter(width = 0.1) +  
        theme(axis.text.x = element_text(angle = 0, hjust = 0.5)) + theme(legend.position = "none")+
        labs(y = "Shannon Diversity", x = "", title = "Geographical location") #+ 
        geom_signif(comparisons = list(c("Ahmednagar", "Pune")), map_signif_level = TRUE) 
#print(p5)

qw <- subset(df, Location %in% c("Ahmednagar", "Pune"))
renu <- wilcox.test(data = qw, index ~ factor(Location))$p.value
wilcox.test(data = qw, index ~factor(Location))
p.adjust(c(0.001,0.01,0.05,0.1), method = "bonferroni")

gridExtra::grid.arrange(p2, p3, p4, p5, nrow = 2)
```