---
title: "PCoA"
output: html_document
---

```{r pcoa, echo=FALSE, message=FALSE, warning=FALSE}
library(microbiome)
library(phyloseq)
library(vegan)
library(knitr)
library(knitcitations)
library(microbiome)
library(ggplot2)
library(dplyr)
library(reshape2)
library(DESeq2)
library(Cairo)
library(gridExtra)

opts_chunk$set(dev="CairoPNG")
knitr::opts_chunk$set(fig.path="output/figure_pcoa/")

method <- "PCoA"
trans <- "compositional"
distance <- "bray"
phylo <- readRDS("inputdata/processed/phyloseq/phyloseq.RDS")
```

## *Principal Coordinates Analysis (PCoA)*

* Ordination method: `r method`
* Dissimilarity measure: `r distance`

```{r PCoA, echo=FALSE, message=FALSE, fig.width=25, fig.height=30, fig.show="hold", warning=FALSE}
theme_set(theme_bw(30))

p1 <- plot_landscape(microbiome::transform(phylo, "compositional"),
                    distance = distance,
                    method = method,
                    size = 5,
                    col = "Diet",
                    shading = FALSE)+
  scale_colour_brewer(palette = "Set1")	+ labs(title = "Diet") + theme(legend.position = 'bottom', legend.text=element_text(size=20), legend.title=element_text(size=25))


p2 <- plot_landscape(microbiome::transform(phylo, "compositional"),
                    distance = distance,
                    method = method,
                    size = 5,
                    col = "Age",
                    shading = FALSE)+
  scale_colour_brewer(palette = "Set1")	+ labs(title = "Age") + theme(legend.position = 'bottom', legend.text=element_text(size=20), legend.title=element_text(size=25))

p3 <- plot_landscape(microbiome::transform(phylo, "compositional"),
                    distance = distance,
                    method = method,
                    size = 5,
                    col = "Gender",
                    shading = FALSE)+
  scale_colour_brewer(palette = "Set1")	+ labs(title = "Gender") + theme(legend.position = 'bottom', legend.text=element_text(size=20), legend.title=element_text(size=25))

p4 <- plot_landscape(microbiome::transform(phylo, "compositional"),
                    distance = distance,
                    method = method,
                    size = 5,
                    col = "Location",
                    shading = FALSE)+
  scale_colour_brewer(palette = "Set1")	+ labs(title = "Location") + theme(legend.position = 'bottom', legend.text=element_text(size=20), legend.title=element_text(size=25))

p5 <- plot_landscape(microbiome::transform(phylo, "compositional"),
                    distance = distance,
                    method = method,
                    size = 5,
                    col = "Family",
                    shading = FALSE)+
  scale_colour_brewer(palette = "Set1")	+ labs(title = "Family") + theme(legend.position = 'bottom', legend.text=element_text(size=20), legend.title=element_text(size=25))
         
gridExtra::grid.arrange(p1, p2, p3, p4, p5, nrow = 2)
```


