---
title: "Tables"
author: "Renuka"
date: "2023-05-09"
output: html_document
---

##Table 1 

```{r table1, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE}
library(pacman)
library(flextable)
library(dplyr)
library(officer)
#p_load(flextable, dplyr, officer)
library(data.table)

df <- tibble::tribble(
  ~Family, ~t,	~Members,	~c, ~G1,	~G2, ~G3, ~b, ~Vegetarian,	~Mixed, ~bl, ~Male,  ~Female, ~bla,	~Pune, ~Ahmednagar, ~blan, ~Adult, ~Middleage, ~Elderly,
"A",  NA, 5,  NA, 1, 2,  2, NA, 5, 0,  NA,  2, 3,   NA,   0, 5,   NA,  1, 2, 2, 
"B",  NA, 3, NA,  1, 1, 1,  NA, 3, 0, NA,  2,  1,   NA,   0, 3,  NA,   1, 1, 1,
"C", NA,  5, NA,  2, 2, 1, NA, 5, 0, NA,   3,  2,  NA,    5, 0,    NA,  2, 2, 1,
"D", NA, 3, NA,  1, 1, 1, NA, 3, 0, NA,   0,  3,  NA,    0, 3,    NA,  1, 1, 1,
"E",  NA, 4,  NA, 1, 2,  1, NA, 0, 4,  NA,  2, 2,   NA,   0, 4,   NA,  2, 1, 1, 
"F",  NA, 5,  NA, 1, 2,  2, NA, 1, 4,  NA,  2, 3,   NA,   5, 0,   NA,  1, 2, 2,
"G", NA,  5, NA,  2, 2, 1, NA, 5, 0, NA,   3,  2,  NA,    5, 0,    NA,  2, 2, 1,
"H", NA,  5, NA,  2, 2, 1, NA, 5, 0, NA,   2,  3,  NA,    5, 0,    NA,  2, 2, 1,
"I", NA,  6, NA,  2, 2, 2, NA, 6, 0, NA,   3,  3,  NA,    6, 0,    NA,  2, 2, 2,
"J", NA,  5, NA,  2, 2, 1, NA, 0, 5, NA,   2,  3,  NA,    5, 0,    NA,  2, 2, 1,
"K", NA,  5, NA,  1, 2, 2, NA, 5, 0, NA,   3,  2,  NA,    0, 5,    NA,  2, 1, 2,
"L",  NA, 4,  NA, 1, 2,  1, NA, 4, 0,  NA,  2, 2,   NA,   4, 0,   NA,  1, 2, 1,
"M",  NA, 5,  NA, 1, 2,  2, NA, 5, 0,  NA,  2, 3,   NA,   5, 0,   NA,  1, 2, 2,
"N",  NA, 5,  NA, 1, 2,  2, NA, 3, 2,  NA,  1, 4,   NA,   5, 0,   NA,  1, 2, 2,
"0",  NA, 7,  NA, 4, 2,  1, NA, 7, 0,  NA,  4, 3,   NA,   7, 0,   NA,  4, 2, 1
 )
ft <- flextable(df)
ft <- delete_part(x = ft, part = "header")

ft <- add_header_row(
   ft, 
   values = c(
     "(n=15)", "",	"(n=72)",	 "", "(n=32)",	"(n=28)", "(n=21)", "", "(n=57)",	"(n=15)", "", "(n=33)",  "(n=39)", "",	"(n=52)", "(n=20)", "", "(n=25)", "(n=26)", "(n=21)"), 
   top = TRUE 
 )

ft <- add_header_row(
   ft, 
   values = c(
     "",	"",	"", "", "G1",	"G2", "G3", "", "Vegetarian",	"Mixed", "", "Male",  "Female", "",	"Pune", "Ahmednagar", "", "Adult", "Middle age", "Elderly"), 
   top = TRUE 
 )

# Add the second row of the multilevel header
ft <- add_header_row(ft, values = c("Family", "", "Members", "", "Generation", "", "Diet", "", "Gender", "", "Location", "", "Age"),
                       colwidths = c(1, 1, 1, 1, 3, 1, 2, 1, 2, 1, 2, 1, 3), top = TRUE)

ft <- theme_booktabs(ft, bold_header = TRUE)
ft <- align(ft, part = "all", i = NULL, j = NULL, align = "center")

# Add custom borders under multi-level headers

# First define define the style of the border line
border_style = officer::fp_border(color="black", width= 1)
ft <- hline(ft, part="header", i = 2, j = c(5:7, 9:10, 12:13, 15:16, 18:20), border = border_style)
ft <- hline(ft, part="header", i = 1, j = c(1, 3, 5:7, 9:10, 12:13, 15:16, 18:20), border = border_style)
ft
```


##Table 2

```{r tab, echo=FALSE, error=FALSE, message=FALSE}
library(pacman)
library(data.table)

df <- tibble::tribble(
  ~Factors,  	~R2,       	~p,
  "Diet",    	0.002,     	0.923,   
  "Age", 	    0.020,     	0.317,  
  "Sex",  	0.008,	      0.467,
  "Location",	0.000,     	0.001,
  "Family", 	0.278,     	0.001
 )

# Set universal border color as black; otherwise it will will be dark grey.
set_flextable_defaults(border.color = "black")

# Create a flextable based on the dataset above
ft <- flextable(df)

ftt <- set_header_labels(ft, values = c( Factors = "Factor",
     R2 = "R2",
     p = "p-value"))
ft_1 <- theme_booktabs(ftt, bold_header = TRUE)
#ft_1 <- align(ft_1, i = 1, j = NULL, align = "center", part = "all")
ft5 <- add_footer_lines(ft_1, "Note- The p-value indicates level of significance <0.001∗∗∗, <0.01∗∗, <0.05∗, 0.1 ns")
ft6 <- set_table_properties(ft5, width = 0.5, layout = "autofit")
ft6 <- align(ft6, part = "all", i = NULL, j = NULL, align = "center")
ft7 <- fontsize(ft6, i = NULL, j = NULL, size = 11, part = "footer")
ft7
```

##Table 3 

```{r ta, echo=FALSE, error=FALSE, message=FALSE}
library(pacman)
library(data.table)

df <- tibble::tribble(
  ~Phylum,       ~Mean,    ~Median ,   ~Prevalence,   ~IQR,
  "Firmicutes",     73.0,      93.5,           100,  53.9,
  "Proteobacteria", 23.8,       2.6,         97.2,  49.3,
  "Actinobacteria", 3.2,       1.2,         90.2,   2.42
 )
# Set universal border color as black; otherwise it will will be dark grey.
set_flextable_defaults(border.color = "black")

# Create a flextable based on the dataset above
ft <- flextable(df)

ftt <- set_header_labels(ft, values = c( Phylum = "Phylum",
     Mean = "Mean relative abundance (%)",
     Median = "Median (%)",
     Prevalence = "Prevalence (%)",
     IQR = "Inter quartile range"))
ft_1 <- theme_booktabs(ftt, bold_header = TRUE)
ft_1 <- align(ft_1, i = NULL, j = NULL, align = "center", part = "all")
ft_2 <- italic(ft_1, i = NULL, j = "Phylum", italic = TRUE, part = "body")
#ft_3 <- align(ft_2, i = 1, j = NULL, align = "right", part = "all")
ft_4 <- align(ft_2, i = NULL, j = NULL, align = "center", part = "all")
ft_4
```

##Table 4

```{r table4, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE}
library(pacman)
library(data.table)

da <- tibble::tribble(
  ~Genus,       ~Mean,    ~Median ,   ~Prevalence,  ~IQR, 
  "Staphylococcus",     50.9,   	60.2,	      100,   91.8,    
  "Bacillus",     	16.3,     	0.3,        	87.5,  12.9,
  "Pseudomonas",   	9.2,     	0.1,          	61.1,  4.98,
  "Anaerococcus", 	1.7,   	0.0,          	38.9,    0.26,
  "Corynebacterium", 	1.0,	0.2,	          73.6,    0.91,
  "Dermabacter",     	0.4,   	0.0,     	40.2,         0.61
 )
# Set universal border color as black; otherwise it will will be dark grey.
set_flextable_defaults(border.color = "black")

# Create a flextable based on the dataset above
ta <- flextable(da)

taa <- set_header_labels(ta, values = c( Genus = "Genus",
     Mean = "Mean relative abundance (%)", 
     Median = "Median (%)",
     Prevalence = "Prevalence (%)",
     IQR = "Inter quartile range (%)"))

ft_1 <- theme_booktabs(taa, bold_header = TRUE)
ft_1 <- align(ft_1, i = NULL, j = NULL, align = "center", part = "all")
ft_2 <- italic(ft_1, i = NULL, j = "Genus", italic = TRUE, part = "body")
ft_2
```


##Supplementary table 1

```{r tab, echo=FALSE, error=FALSE, message=FALSE}
library(pacman)
p_load(flextable, dplyr, officer)
library(data.table)

df <- tibble::tribble(
   ~Genus,             ~Family,      	~p,
   "Staphylococcus",   "A-C",    	 0.07,     	 
  "Staphylococcus",    "C-E", 	     0.01,     	
  "Staphylococcus",     "E-F",  	  0.02,	      
  "Staphylococcus",     "A-N",	    0.08,     	
  "Staphylococcus",     "E-N",     0.01,
  "Bacillus",          "E-H",     0.04
 )

# Set universal border color as black; otherwise it will will be dark grey.
set_flextable_defaults(border.color = "black")

# Create a flextable based on the dataset above
ft <- flextable(df)

ftt <- set_header_labels(ft, values = c( Genus = "Genus", 
                                         Family = "Family comparison",
                                          p = "p-value"))
ft_1 <- theme_booktabs(ftt, bold_header = TRUE)
#ft_1 <- align(ft_1, i = 1, j = NULL, align = "center", part = "all")
ft5 <- add_footer_lines(ft_1, "Note- The p-value indicates level of significance <0.001∗∗∗, <0.01∗∗, <0.05∗, 0.1 ns")
ft6 <- set_table_properties(ft5, width = 0.5, layout = "autofit")
ft6 <- align(ft6, part = "all", i = NULL, j = NULL, align = "center")
ft7 <- fontsize(ft6, i = NULL, j = NULL, size = 11, part = "footer")
ft7
ft_8 <- italic(ft7, i = NULL, j = "Genus", italic = TRUE, part = "body")
```



##Updated Supplementary table 1 with 1/100 DAA for family

```{r tab, echo=FALSE, error=FALSE, message=FALSE}
library(pacman)
p_load(flextable, dplyr, officer)
library(data.table)

df <- tibble::tribble(
   ~Genus,             ~Family,      	~p,
   "Bacillus",          "A-C",     0.02,
   "Bacillus",          "C-E",     0.01,
   "Bacillus",          "A-F",     0.01,
   "Bacillus",          "E-F",     0.01,
   "Bacillus",          "E-I",     0.02,
   "Bacillus",          "C-K",     0.01,
   "Bacillus",          "F-K",     0.02,
   "Bacillus",          "A-L",     0.04,
   "Bacillus",          "E-L",     0.01,
   "Bacillus",          "A-N",     0.01,
   "Bacillus",          "E-N",     0.00,
   "Bacillus",          "K-N",     0.01,
   "Bacillus",          "E-O",     0.01,
   "Staphylococcus",   "B-H",    	 0.05,     	 
  "Staphylococcus",    "D-H", 	   0.04,     	
  "Staphylococcus",     "E-H",  	 0.02,	      
  "Staphylococcus",     "E-I",	   0.05,     	
  "Anaerococcus",      "B-C",     0.05,
   "Anaerococcus",      "B-D",    0.01, 
   "Anaerococcus",      "B-E",    0.01,
   "Anaerococcus",      "B-F",    0.02,
   "Anaerococcus",      "B-H",    0.02,
   "Anaerococcus",      "E-L",    0.05,
   "Anaerococcus",      "D-M",    0.02,
   "Anaerococcus",      "E-M",    0.03,
   "Anaerococcus",      "F-M",    0.05,
  "klebsiella",         "A-B",    0.05
 )

# Set universal border color as black; otherwise it will will be dark grey.
set_flextable_defaults(border.color = "black")

# Create a flextable based on the dataset above
ft <- flextable(df)

ftt <- set_header_labels(ft, values = c( Genus = "Genus", 
                                         Family = "Family comparison",
                                          p = "p-value"))
ft_1 <- theme_booktabs(ftt, bold_header = TRUE)
#ft_1 <- align(ft_1, i = 1, j = NULL, align = "center", part = "all")
ft5 <- add_footer_lines(ft_1, "Note- The p-value indicates level of significance <0.001∗∗∗, <0.01∗∗, <0.05∗, 0.1 ns")
ft6 <- set_table_properties(ft5, width = 0.5, layout = "autofit")
ft6 <- align(ft6, part = "all", i = NULL, j = NULL, align = "center")
ft7 <- fontsize(ft6, i = NULL, j = NULL, size = 11, part = "footer")
ft7
ft_8 <- italic(ft7, i = NULL, j = "Genus", italic = TRUE, part = "body")
```



##Updated Supplementary table 2 with 1/100 DAA for LOctaion

```{r tab, echo=FALSE, error=FALSE, message=FALSE}
library(pacman)
p_load(flextable, dplyr, officer)
library(data.table)

df <- tibble::tribble(
   ~Genus,             ~chi,      	~df,      ~p,
   "Staphylococcus",    19.81,     1,        0.00,
   "Xanthomonas",       3.76,      1,        0.05,
   "Jeotgalibacillus",  8.69,      1,        0.00,
   "Amycolatopsis",     7.44,      1,        0.00,
   "Komagataeibacter",  7.69,      1,        0.00,
   "Novispirillum",     6.3,      1,         0.01,
   "Tuberibacillus",    4.14,   1,           0.04,
   "Nesterenkonia",     9.45,     1,         0.00,
   "Terribacillus",     8.98,    1,          0.00,
   "Sporosarcina",      12.06,   1,          0.00,
   "Lentibacillus",      5.27,    1,         0.02,
   "Geothrix",          10.2,    1,          0.00,
   "Dietzia",          6.62,    1,          0.01,
   "Planococcus",   15.72,        1,        0.00,
  "Gracilibacillus",    9.39,     1,        0.00,
  "Geobacillus",     9.34,        1,        0.00,
  "Ornithinibacillus", 25.06,     1,        0.00,
  "Oceanobacillus",      15.45,   1,        0.00,
   "Domibacillus",      3.96,     1,        0.04,
   "Paracoccus",      15.80,      1,        0.00,
   "Paenibacillus",      20.82,   1,        0.00,
   "Virgibacillus",      23.29,   1,        0.00,
   "Brachybacterium",   6.88,     1,        0.00,
   "Stenotrophomonas",  6.77,    1,        0.00
    )

# Set universal border color as black; otherwise it will will be dark grey.
set_flextable_defaults(border.color = "black")

# Create a flextable based on the dataset above
ft <- flextable(df)

ftt <- set_header_labels(ft, values = c( Genus = "Genus", 
                                         chi = "chi square",
                                         df = "df",
                                          p = "p-value"))
ft_1 <- theme_booktabs(ftt, bold_header = TRUE)
#ft_1 <- align(ft_1, i = 1, j = NULL, align = "center", part = "all")
ft5 <- add_footer_lines(ft_1, "Note- The p-value indicates level of significance <0.001∗∗∗, <0.01∗∗, <0.05∗, 0.1 ns")
ft6 <- set_table_properties(ft5, width = 0.5, layout = "autofit")
ft6 <- align(ft6, part = "all", i = NULL, j = NULL, align = "center")
ft7 <- fontsize(ft6, i = NULL, j = NULL, size = 11, part = "footer")
ft7
ft_8 <- italic(ft7, i = NULL, j = "Genus", italic = TRUE, part = "body")
```

##Updated with Dr Richa_ Supplementary table 2 with 1/100 DAA for LOctaion

```{r tab, echo=FALSE, error=FALSE, message=FALSE}
library(pacman)
p_load(flextable, dplyr, officer)
library(data.table)

df <- tibble::tribble(
    ~Family,   ~Locationo,   ~locationt,  	~Genus,       ~p,
   "A-C",      "Ahmednagar",   "Pune",      "Bacillus",   0.02,
   "A-F",     "Ahmednagar",   "Pune",      "Bacillus",    0.01,
   "A-L",     "Ahmednagar",   "Pune",      "Bacillus",    0.04,
   "A-N",     "Ahmednagar",   "Pune",      "Bacillus",    0.01,
   "B-D",     "Ahmednagar",   "Ahmednagar", "Anaerococcus", 0.01,
  "B-E",      "Ahmednagar",   "Ahmednagar", "Anaerococcus", 0.01,
  "B-C",      "Ahmednagar",   "Pune",       "Anaerococcus", 0.05,
  "B-F",      "Ahmednagar",   "Pune",       "Anaerococcus", 0.02,
  "B-G",       "Ahmednagar",   "Pune",       "Anaerococcus", 0.07,
  "B-H",       "Ahmednagar",   "Pune",       "Anaerococcus", 0.02,
  "B-H",       "Ahmednagar",   "Pune",       "Staphylococcus", 0.05,
  "C-E",       "Pune",         "Ahmednagar",   "Bacillus",   0.01,
  "C-K",       "Pune",         "Ahmednagar",    "Bacillus",   0.01,
   "D-H",      "Ahmednagar",   "Pune",       "Staphylococcus", 0.04,
   "D-M",      "Ahmednagar",   "Pune",       "Anaerococcus", 0.02
 )

# Set universal border color as black; otherwise it will will be dark grey.
set_flextable_defaults(border.color = "black")

# Create a flextable based on the dataset above
ft <- flextable(df)

ftt <- set_header_labels(ft, values = c(Family = "Family comparison",
                                        Locationo= ""
                                        Genus = "Genus",
                                          p = "p-value"))
ft_1 <- theme_booktabs(ftt, bold_header = TRUE)
#ft_1 <- align(ft_1, i = 1, j = NULL, align = "center", part = "all")
ft5 <- add_footer_lines(ft_1, "Note- The p-value indicates level of significance <0.001∗∗∗, <0.01∗∗, <0.05∗, 0.1 ns")
ft6 <- set_table_properties(ft5, width = 0.5, layout = "autofit")
ft6 <- align(ft6, part = "all", i = NULL, j = NULL, align = "center")
ft7 <- fontsize(ft6, i = NULL, j = NULL, size = 11, part = "footer")
ft7
ft_8 <- italic(ft7, i = NULL, j = "Genus", italic = TRUE, part = "body")
```
