---
title: "updatedcomp"
author: "Renuka"
date: "2023-09-18"
output: html_document
---
Location-wise G2 couple- unrlated comparisions

```{r Lg2g2, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
library(ggsignif)
library(mia)
library(vegan)
library(scater)
library(dplyr)
library(tidyverse)
library(magrittr)
tse <- readRDS("inputdata/processed/TSE/fam_tse.rds")
di <- as.matrix(vegdist(t(assay(tse, "counts")), method="bray"))
di <- reshape2::melt(di) %>% `colnames<-`(c("X","Y", "value"))

tse_list <- splitOn(tse, f= "Location")
tse_Ahmednagar <- tse_list[[1]]
tse_Pune <- tse_list[[2]]

# subsetting and filtering data
tse_Ahmednagar <- tse_Ahmednagar[ , tse_Ahmednagar$G %in% "G2"]
tse_Ahmednagar <- tse_Ahmednagar[,!(colnames(tse_Ahmednagar) %in% c("B2", "D2"))]

set.seed(123)
within_pairs <- colData(tse_Ahmednagar) %>% as_tibble() %>% group_by(Family) %>%
    summarise(within_pairs=combn(Sample, 2, simplify = FALSE)) %>% 
    select(within_pairs) %>% .[[1]] %>% do.call(rbind, .) %>% 
    as.data.frame() %>% `colnames<-`(c("pair_1", "pair_2")) 
rand <- sample(nrow(within_pairs))
between_pairs <- data.frame(pair_1=within_pairs$pair_1, pair_2=within_pairs$pair_2[rand])

ANdf <- rbind(
    merge(di, within_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
        mutate(grp=rep("within_pairs",nrow(within_pairs))),
    merge(di, between_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
        mutate(grp=rep("between_pairs",nrow(between_pairs)))
)

tse_Pune <- tse_list[[2]]
# subsetting and filtering data
tse_Pune  <- tse_Pune [ , tse_Pune$G %in% "G2"]


set.seed(123)
within_pairs <- colData(tse_Pune) %>% as_tibble() %>% group_by(Family) %>%
    summarise(within_pairs=combn(Sample, 2, simplify = FALSE)) %>% 
    select(within_pairs) %>% .[[1]] %>% do.call(rbind, .) %>% 
    as.data.frame() %>% `colnames<-`(c("pair_1", "pair_2")) 
rand <- sample(nrow(within_pairs))
between_pairs <- data.frame(pair_1=within_pairs$pair_1, pair_2=within_pairs$pair_2[rand])

PNdf <- rbind(
    merge(di, within_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
        mutate(grp=rep("within_pairs",nrow(within_pairs))),
    merge(di, between_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
        mutate(grp=rep("between_pairs",nrow(between_pairs)))
)

mergedcities <- rbind(ANdf, PNdf)
mergedcities$City <- c(rep("Ahmednagar", nrow(ANdf)),  rep("Pune", nrow(PNdf)))
g <- ggplot(mergedcities, aes(x=grp,y=value))+
    geom_boxplot(outlier.shape = NA)+
    geom_jitter(aes(colour = City), width= 0.05, size= 1.7) +
    geom_signif(comparisons = list(c("within_pairs", "between_pairs"))) + theme(text = element_text(size = 10)) + labs(x = "", y= "Bray-Curtis index", title = "Locationwise G2-G2 comparison") + scale_x_discrete(labels=c("within_pairs" = "Within family", "between_pairs" = "Between family")) + theme_bw(base_size = 20)
print(g)
```


Location-wise G2-G3

```{r Lg2g3, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
library(ggsignif)
library(mia)
library(vegan)
library(scater)
library(dplyr)
library(tidyverse)
library(magrittr)

tse <- readRDS("inputdata/processed/TSE/fam_tse.rds")
di <- as.matrix(vegdist(t(assay(tse, "counts")), method="bray"))
di <- reshape2::melt(di) %>% `colnames<-`(c("X","Y", "value"))

# subsetting and filtering data for g2 single member
tse4 <- tse[ , tse$G %in% "G2"]
tse4 <- tse4[,!(colnames(tse4) %in% c("B2", "D2"))]
tse4 <- tse4[ , tse4$Gender %in% "Male"]

# subsetting and filtering data for g3 single member
tse5 <- tse[ , tse$G %in% "G3"]
tse5 <- tse5[,!(colnames(tse5) %in% c("A5", "B3", "D3", "F5", "I6", "K5", "M5", "N5"))]

##merging two tse
tse6 <- mergeSEs(list(tse4, tse5), join = "inner")

#spling location-wise
tse_list <- splitOn(tse6, f= "Location")
tse_Ahmdg2g3 <- tse_list[[1]]
tse_Puneg2g3 <- tse_list[[2]]


set.seed(123)
within_pairs <- colData(tse_Ahmdg2g3) %>% as_tibble() %>% group_by(Family) %>%
    summarise(within_pairs=combn(Sample, 2, simplify = FALSE)) %>% 
    select(within_pairs) %>% .[[1]] %>% do.call(rbind, .) %>% 
    as.data.frame() %>% `colnames<-`(c("pair_1", "pair_2")) 
rand <- sample(nrow(within_pairs))
between_pairs <- data.frame(pair_1=within_pairs$pair_1, pair_2=within_pairs$pair_2[rand])

#between_pairs <- lapply(unique(colData(tse_Ahmdg2g3)$Family), function(fam) {
 #   set.seed(123)
#    pair_1 <- colData(tse_Ahmdg2g3) %>% as_tibble() %>% 
#    filter(Family==fam) %>% sample_n(1)
#    set.seed(123)
#    pair_2 <- colData(tse_Ahmdg2g3) %>% as_tibble() %>% 
#    filter(Family!=fam & Gender!=pair_1$Gender) %>% sample_n(1)
#    c(pair_1$Sample, pair_2$Sample)
#}) %>% do.call(rbind, .) %>% 
 #   as.data.frame() %>% `colnames<-`(c("pair_1", "pair_2"))


ANg2g3 <- rbind(
    merge(di, within_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
        mutate(grp=rep("within_pairs",nrow(within_pairs))),
    merge(di, between_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
        mutate(grp=rep("between_pairs",nrow(between_pairs)))
)

tse_Puneg2g3 <- tse_list[[2]]

set.seed(123)
within_pairs <- colData(tse_Puneg2g3) %>% as_tibble() %>% group_by(Family) %>%
    summarise(within_pairs=combn(Sample, 2, simplify = FALSE)) %>% 
    select(within_pairs) %>% .[[1]] %>% do.call(rbind, .) %>% 
    as.data.frame() %>% `colnames<-`(c("pair_1", "pair_2")) 
rand <- sample(nrow(within_pairs))
between_pairs <- data.frame(pair_1=within_pairs$pair_1, pair_2=within_pairs$pair_2[rand])

#between_pairs <- lapply(unique(colData(tse_Puneg2g3)$Family), function(fam) {
#    set.seed(123)
#    pair_1 <- colData(tse_Puneg2g3) %>% as_tibble() %>% 
#    filter(Family==fam) %>% sample_n(1)
#    set.seed(123)
#    pair_2 <- colData(tse_Puneg2g3) %>% as_tibble() %>% 
#    filter(Family!=fam & Gender!=pair_1$Gender) %>% sample_n(1)
#    c(pair_1$Sample, pair_2$Sample)
#}) %>% do.call(rbind, .) %>% 
#    as.data.frame() %>% `colnames<-`(c("pair_1", "pair_2"))


PNg2g3 <- rbind(
    merge(di, within_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
        mutate(grp=rep("within_pairs",nrow(within_pairs))),
    merge(di, between_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
        mutate(grp=rep("between_pairs",nrow(between_pairs)))
)

mergedcities <- rbind(ANg2g3, PNg2g3)
mergedcities$City <- c(rep("Ahmednagar", nrow(ANg2g3)),  rep("Pune", nrow(PNg2g3)))
s <- ggplot(mergedcities, aes(x=grp,y=value))+
    geom_boxplot(outlier.shape = NA)+
    geom_jitter(aes(colour = City), width= 0.05, size= 1.7) +
    geom_signif(comparisons = list(c("within_pairs", "between_pairs"))) + theme(text = element_text(size = 10)) + labs(x = "", y= "Bray-Curtis index", title = "Location-wise G2-G3 related comparisions") + scale_x_discrete(labels=c("within_pairs" = "Within family", "between_pairs" = "Between family")) + theme_bw(base_size = 20)
print(s)
```

#Same as previous commands

```{r prevLg2g2, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
library(ggsignif)
library(mia)
library(vegan)
library(scater)
library(dplyr)
library(tidyverse)
library(magrittr)

tse <- readRDS("inputdata/processed/TSE/fam_tse.rds")
di <- as.matrix(vegdist(t(assay(tse, "counts")), method="bray"))
di <- reshape2::melt(di) %>% `colnames<-`(c("X","Y", "value"))

# subsetting and filtering data for g2 single member
tse4 <- tse[ , tse$G %in% "G2"]
tse4 <- tse4[,!(colnames(tse4) %in% c("B2", "D2"))]
tse4 <- tse4[ , tse4$Gender %in% "Male"]

# subsetting and filtering data for g3 single member
tse5 <- tse[ , tse$G %in% "G3"]
tse5 <- tse5[,!(colnames(tse5) %in% c("A5", "B3", "D3", "F5", "I6", "K5", "M5", "N5"))]

##merging two tse
tse6 <- mergeSEs(list(tse4, tse5), join = "inner")

#spling location-wise
tse_list <- splitOn(tse6, f= "Location")
tse_Ahmdg2g3 <- tse_list[[1]]
tse_Puneg2g3 <- tse_list[[2]]


set.seed(123)
within_pairs <- colData(tse_Ahmdg2g3) %>% as_tibble() %>% group_by(Family) %>%
    summarise(within_pairs=combn(Sample, 2, simplify = FALSE)) %>% 
    select(within_pairs) %>% .[[1]] %>% do.call(rbind, .) %>% 
    as.data.frame() %>% `colnames<-`(c("pair_1", "pair_2")) 

between_pairs <- lapply(unique(colData(tse_Ahmdg2g3)$Family), function(fam) {
    set.seed(123)
    pair_1 <- colData(tse_Ahmdg2g3) %>% as_tibble() %>% 
    filter(Family==fam) %>% sample_n(1)
    set.seed(123)
    pair_2 <- colData(tse_Ahmdg2g3) %>% as_tibble() %>% 
    filter(Family!=fam & Gender!=pair_1$Gender) %>% sample_n(1)
    c(pair_1$Sample, pair_2$Sample)
}) %>% do.call(rbind, .) %>% 
    as.data.frame() %>% `colnames<-`(c("pair_1", "pair_2"))


ANg2g3 <- rbind(
    merge(di, within_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
        mutate(grp=rep("within_pairs",nrow(within_pairs))),
    merge(di, between_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
        mutate(grp=rep("between_pairs",nrow(between_pairs)))
)

tse_Puneg2g3 <- tse_list[[2]]

set.seed(123)
within_pairs <- colData(tse_Puneg2g3) %>% as_tibble() %>% group_by(Family) %>%
    summarise(within_pairs=combn(Sample, 2, simplify = FALSE)) %>% 
    select(within_pairs) %>% .[[1]] %>% do.call(rbind, .) %>% 
    as.data.frame() %>% `colnames<-`(c("pair_1", "pair_2")) 

between_pairs <- lapply(unique(colData(tse_Puneg2g3)$Family), function(fam) {
    set.seed(123)
    pair_1 <- colData(tse_Puneg2g3) %>% as_tibble() %>% 
    filter(Family==fam) %>% sample_n(1)
    set.seed(123)
    pair_2 <- colData(tse_Puneg2g3) %>% as_tibble() %>% 
    filter(Family!=fam & Gender!=pair_1$Gender) %>% sample_n(1)
    c(pair_1$Sample, pair_2$Sample)
}) %>% do.call(rbind, .) %>% 
    as.data.frame() %>% `colnames<-`(c("pair_1", "pair_2"))


PNg2g3 <- rbind(
    merge(di, within_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
        mutate(grp=rep("within_pairs",nrow(within_pairs))),
    merge(di, between_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
        mutate(grp=rep("between_pairs",nrow(between_pairs)))
)

mergedcities <- rbind(ANg2g3, PNg2g3)
mergedcities$City <- c(rep("Ahmednagar", nrow(ANg2g3)),  rep("Pune", nrow(PNg2g3)))
s <- ggplot(mergedcities, aes(x=grp,y=value))+
    geom_boxplot(outlier.shape = NA)+
    geom_jitter(aes(colour = City), width= 0.05, size= 1.7) +
    geom_signif(comparisons = list(c("within_pairs", "between_pairs"))) + theme(text = element_text(size = 10)) + labs(x = "", y= "Bray-Curtis index", title = "Location-wise G2-G3 related comparisions") + scale_x_discrete(labels=c("within_pairs" = "Within family", "between_pairs" = "Between family")) + theme_bw(base_size = 20)
print(s)
```

G1-G3

```{r Lg1g3, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
library(ggsignif)
library(mia)
library(vegan)
library(scater)
library(dplyr)
library(tidyverse)
library(magrittr)

tse <- readRDS("inputdata/processed/TSE/fam_tse.rds")
di <- as.matrix(vegdist(t(assay(tse, "counts")), method="bray"))
di <- reshape2::melt(di) %>% `colnames<-`(c("X","Y", "value"))

# subsetting and filtering data for g1 single member
tse7 <- tse[ , tse$G %in% "G1"]
tse7 <- tse7[,!(colnames(tse7) %in% c("B1", "D1", "O3","C2", "G1", "H2", "I1", "J1", "O1", "O4"))]
#tse7 <- tse7[ , tse7$Gender %in% "Male"]

# subsetting and filtering data for g3 single member
tse5 <- tse[ , tse$G %in% "G3"]
tse5 <- tse5[,!(colnames(tse5) %in% c("A5", "B3", "D3", "F5", "I6", "K5", "M5", "N5"))]

##merging two tse
tse8 <- mergeSEs(list(tse7, tse5), join = "inner")

#spling location-wise
tse_list <- splitOn(tse8, f= "Location")
tse_Ahmdg1g3 <- tse_list[[1]]
tse_Puneg1g3 <- tse_list[[2]]


set.seed(123)
within_pairs <- colData(tse_Ahmdg1g3) %>% as_tibble() %>% group_by(Family) %>%
    summarise(within_pairs=combn(Sample, 2, simplify = FALSE)) %>% 
    select(within_pairs) %>% .[[1]] %>% do.call(rbind, .) %>% 
    as.data.frame() %>% `colnames<-`(c("pair_1", "pair_2")) 
rand <- sample(nrow(within_pairs))
between_pairs <- data.frame(pair_1=within_pairs$pair_1, pair_2=within_pairs$pair_2[rand])

#between_pairs <- lapply(unique(colData(tse_Ahmdg2g3)$Family), function(fam) {
 #   set.seed(123)
#    pair_1 <- colData(tse_Ahmdg2g3) %>% as_tibble() %>% 
#    filter(Family==fam) %>% sample_n(1)
#    set.seed(123)
#    pair_2 <- colData(tse_Ahmdg2g3) %>% as_tibble() %>% 
#    filter(Family!=fam & Gender!=pair_1$Gender) %>% sample_n(1)
#    c(pair_1$Sample, pair_2$Sample)
#}) %>% do.call(rbind, .) %>% 
 #   as.data.frame() %>% `colnames<-`(c("pair_1", "pair_2"))


ANg1g3 <- rbind(
    merge(di, within_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
        mutate(grp=rep("within_pairs",nrow(within_pairs))),
    merge(di, between_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
        mutate(grp=rep("between_pairs",nrow(between_pairs)))
)

tse_Puneg1g3 <- tse_list[[2]]

set.seed(123)
within_pairs <- colData(tse_Puneg1g3) %>% as_tibble() %>% group_by(Family) %>%
    summarise(within_pairs=combn(Sample, 2, simplify = FALSE)) %>% 
    select(within_pairs) %>% .[[1]] %>% do.call(rbind, .) %>% 
    as.data.frame() %>% `colnames<-`(c("pair_1", "pair_2")) 
rand <- sample(nrow(within_pairs))
between_pairs <- data.frame(pair_1=within_pairs$pair_1, pair_2=within_pairs$pair_2[rand])

#between_pairs <- lapply(unique(colData(tse_Puneg2g3)$Family), function(fam) {
#    set.seed(123)
#    pair_1 <- colData(tse_Puneg2g3) %>% as_tibble() %>% 
#    filter(Family==fam) %>% sample_n(1)
#    set.seed(123)
#    pair_2 <- colData(tse_Puneg2g3) %>% as_tibble() %>% 
#    filter(Family!=fam & Gender!=pair_1$Gender) %>% sample_n(1)
#    c(pair_1$Sample, pair_2$Sample)
#}) %>% do.call(rbind, .) %>% 
#    as.data.frame() %>% `colnames<-`(c("pair_1", "pair_2"))


PNg1g3 <- rbind(
    merge(di, within_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
        mutate(grp=rep("within_pairs",nrow(within_pairs))),
    merge(di, between_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
        mutate(grp=rep("between_pairs",nrow(between_pairs)))
)

mergedcities <- rbind(ANg1g3, PNg1g3)
mergedcities$City <- c(rep("Ahmednagar", nrow(ANg1g3)),  rep("Pune", nrow(PNg1g3)))
s <- ggplot(mergedcities, aes(x=grp,y=value))+
    geom_boxplot(outlier.shape = NA)+
    geom_jitter(aes(colour = City), width= 0.05, size= 1.7) +
    geom_signif(comparisons = list(c("within_pairs", "between_pairs"))) + theme(text = element_text(size = 10)) + labs(x = "", y= "Bray-Curtis index", title = "Location-wise G1-G3 related comparisions") + scale_x_discrete(labels=c("within_pairs" = "Within family", "between_pairs" = "Between family")) + theme_bw(base_size = 20)
print(s)
```

G1-G2

```{r Lg1g2, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
library(ggsignif)
library(mia)
library(vegan)
library(scater)
library(dplyr)
library(tidyverse)
library(magrittr)

tse <- readRDS("inputdata/processed/TSE/fam_tse.rds")
di <- as.matrix(vegdist(t(assay(tse, "counts")), method="bray"))
di <- reshape2::melt(di) %>% `colnames<-`(c("X","Y", "value"))

# subsetting and filtering data for g1 single member
tse7 <- tse[ , tse$G %in% "G1"]
tse7 <- tse7[,!(colnames(tse7) %in% c("B1", "D1", "O3","C2", "G1", "H2", "I1", "J1", "O1", "O4"))]
#tse7 <- tse7[ , tse7$Gender %in% "Male"]

# subsetting and filtering data for g2 single member
tse4 <- tse[ , tse$G %in% "G2"]
tse4 <- tse4[,!(colnames(tse4) %in% c("B2", "D2"))]
#tse4 <- tse4[ , tse4$Gender %in% "Male"]
tse4 <- tse4[ , tse4$Gender %in% "Male"]
##merging two tse
tse9 <- mergeSEs(list(tse7, tse4), join = "inner")

#spling location-wise
tse_list <- splitOn(tse9, f= "Location")
tse_Ahmdg1g2 <- tse_list[[1]]
tse_Puneg1g2 <- tse_list[[2]]


set.seed(123)
within_pairs <- colData(tse_Ahmdg1g2) %>% as_tibble() %>% group_by(Family) %>%
    summarise(within_pairs=combn(Sample, 2, simplify = FALSE)) %>% 
    select(within_pairs) %>% .[[1]] %>% do.call(rbind, .) %>% 
    as.data.frame() %>% `colnames<-`(c("pair_1", "pair_2")) 
rand <- sample(nrow(within_pairs))
between_pairs <- data.frame(pair_1=within_pairs$pair_1, pair_2=within_pairs$pair_2[rand])

#between_pairs <- lapply(unique(colData(tse_Ahmdg2g3)$Family), function(fam) {
 #   set.seed(123)
#    pair_1 <- colData(tse_Ahmdg2g3) %>% as_tibble() %>% 
#    filter(Family==fam) %>% sample_n(1)
#    set.seed(123)
#    pair_2 <- colData(tse_Ahmdg2g3) %>% as_tibble() %>% 
#    filter(Family!=fam & Gender!=pair_1$Gender) %>% sample_n(1)
#    c(pair_1$Sample, pair_2$Sample)
#}) %>% do.call(rbind, .) %>% 
 #   as.data.frame() %>% `colnames<-`(c("pair_1", "pair_2"))


ANg1g2 <- rbind(
    merge(di, within_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
        mutate(grp=rep("within_pairs",nrow(within_pairs))),
    merge(di, between_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
        mutate(grp=rep("between_pairs",nrow(between_pairs)))
)

tse_Puneg1g2 <- tse_list[[2]]

set.seed(123)
within_pairs <- colData(tse_Puneg1g2) %>% as_tibble() %>% group_by(Family) %>%
    summarise(within_pairs=combn(Sample, 2, simplify = FALSE)) %>% 
    select(within_pairs) %>% .[[1]] %>% do.call(rbind, .) %>% 
    as.data.frame() %>% `colnames<-`(c("pair_1", "pair_2")) 
rand <- sample(nrow(within_pairs))
between_pairs <- data.frame(pair_1=within_pairs$pair_1, pair_2=within_pairs$pair_2[rand])

#between_pairs <- lapply(unique(colData(tse_Puneg2g3)$Family), function(fam) {
#    set.seed(123)
#    pair_1 <- colData(tse_Puneg2g3) %>% as_tibble() %>% 
#    filter(Family==fam) %>% sample_n(1)
#    set.seed(123)
#    pair_2 <- colData(tse_Puneg2g3) %>% as_tibble() %>% 
#    filter(Family!=fam & Gender!=pair_1$Gender) %>% sample_n(1)
#    c(pair_1$Sample, pair_2$Sample)
#}) %>% do.call(rbind, .) %>% 
#    as.data.frame() %>% `colnames<-`(c("pair_1", "pair_2"))


PNg1g2 <- rbind(
    merge(di, within_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
        mutate(grp=rep("within_pairs",nrow(within_pairs))),
    merge(di, between_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
        mutate(grp=rep("between_pairs",nrow(between_pairs)))
)

mergedcities <- rbind(ANg1g2, PNg1g2)
mergedcities$City <- c(rep("Ahmednagar", nrow(ANg1g2)),  rep("Pune", nrow(PNg1g2)))
s <- ggplot(mergedcities, aes(x=grp,y=value))+
    geom_boxplot(outlier.shape = NA)+
    geom_jitter(aes(colour = City), width= 0.05, size= 1.7) +
    geom_signif(comparisons = list(c("within_pairs", "between_pairs"))) + theme(text = element_text(size = 10)) + labs(x = "", y= "Bray-Curtis index", title = "Location-wise G1-G2 related comparisions") + scale_x_discrete(labels=c("within_pairs" = "Within family", "between_pairs" = "Between family")) + theme_bw(base_size = 20)
print(s)
```